### ISSUE TITLE
You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by cesc1989** [DanielSharkov/svelte-router#4]
Hi, got this error in a Svelte project setup with Webpack

```
ERROR in ./node_modules/@danielsharkov/svelte-router/src/RouterViewport.svelte 1:1
Module parse failed: Unexpected character '#' (1:1)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> {#if componentNotChanged}
| 	<div
| 	in:transition={{ duration, easing, delay }}
 @ ./node_modules/@danielsharkov/svelte-router/src/index.js 3:0-67 3:0-67
 @ ./src/App.svelte
 @ ./src/main.js
 @ multi ./src/main.js
```

**Comment by DanielSharkov** [comment]
I wasn't able to reproduce the same error with the newest router version [3.0.0](https://github.com/DanielSharkov/svelte-router/releases) and the official webpack template [sveltejs/template-webpack](https://github.com/sveltejs/template-webpack).
But I hope this isn't a problem any more, as a lot has been fixed and changed since version 1.0.0.

If your problem still persist, feel free to reopen this issue! 😃
